[snowflake]

user="ripudsp05"
password="Ripudsp05@snowflake"
account="evlealf-wab18231"
database="FIN_DATABASE"
schema="market_data"
warehouse="compute_wh"
role="ACCOUNTADMIN"

SNOWFLAKE_CORTEX_SEARCH_SERVICE="LLMOPS_CORTEX_SEARCH_SERVICE"
NEWS_API_KEY="69af5c0cae6940de94156db81e44477b"
ALPHA_VANTAGE_API_KEY="ZGDHFBMMIBAERR4T"  

[rapidapi]
key="89850a1b53msh25354cdce04e3fap17001djsnda1dd35b6a68"